version: "3.8"

services:
  # Prowlarr - runs through transmission VPN
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:arm64v8-latest
    container_name: prowlarr
    network_mode: "container:transmission-vpn"  # Uses transmission's network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /home/karant/docker-data/arr/prowlarr/config:/config
    restart: unless-stopped

  # Sonarr - TV Shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:arm64v8-latest
    container_name: sonarr
    networks:
      - homelab-net  # Your existing docker network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - NO_CHOWN=true
    volumes:
      - /home/karant/docker-data/arr/sonarr/config:/config
      - /mnt/media/TV:/tv
      - /mnt/media/data/completed:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  # Radarr - Movies
  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    networks:
      - homelab-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - NO_CHOWN=true
    volumes:
      - /home/karant/docker-data/arr/radarr/config:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/data/completed:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  # Readarr - Books
  # readarr:
  #   image: hotio/readarr:nightly
  #   container_name: readarr
  #   networks:
  #     - homelab-net
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Dublin
  #   volumes:
  #     - /home/karant/docker-data/arr/readarr/config:/config
  #     - /mnt/media/Books:/books
  #     - /mnt/media/data/completed:/downloads
  #   ports:
  #     - "8787:8787"
  #   restart: unless-stopped

  # Lidarr - Music
  lidarr:
    image: lscr.io/linuxserver/lidarr:arm64v8-latest
    container_name: lidarr
    networks:
      - homelab-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - NO_CHOWN=true
    volumes:
      - /home/karant/docker-data/arr/lidarr/config:/config
      - /mnt/media/Music:/music
      - /mnt/media/data/completed:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

networks:
  homelab-net:
    external: true  # Uses your existing network