version: "3.8"

services:
  # Prowlarr - runs through transmission VPN
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:arm64v8-latest
    container_name: prowlarr
    network_mode: "container:transmission-vpn"  # Uses transmission's network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /home/karant/docker-data/arr/prowlarr/config:/config
    restart: unless-stopped

networks:
  homelab-net:
    external: true  # Uses your existing network