---
title: "My Homelab"
subtitle: "Bosgame Mini PC (R7 6800H + 32 GB DDR5) | Tailscale Network"
logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homer.png"
favicon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homebox.png"
theme: walkxcode
header: false
footer: false

columns: "3"
connectivityCheck: true

proxy:
  useCredentials: false

links:
  - name: "Poolsuite"
    icon: "fas fa-umbrella-beach"
    url: "https://poolsuite.net/"
    target: "_blank"
  - name: "Cloudflare"
    icon: "fas fa-cloud"
    url: "https://dash.cloudflare.com/488fdd875f76300295df136c8b5466db/example.com/dns/records"
    target: "_blank"
  - name: "Tailscale Admin"
    icon: "fas fa-network-wired"
    url: "https://login.tailscale.com/admin"
    target: "_blank"
  - name: "Icons"
    icon: "fas fa-icons"
    url: "https://dashboardicons.com/"
    target: "_blank"
  - name: "Configs"
    icon: "fas fa-code"
    url: "https://code.example.com"
    target: "_blank"

services:
  - name: "System 📊"
    icon: "fas fa-heartbeat"
    items:
      - name: "System Stats"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/synology-vmm.png"
        subtitle: "CPU, RAM, Disk, Network"
        url: "https://stats.example.com"
        target: "_blank"
        type: "Glances"
        endpoint: "https://stats.example.com"
        stats: [cpu, mem]
        # Click → goes to stats.example.com
        # Stats → fetched from localhost:61208
      
      - name: "AdGuard Home"
        type: "AdGuardHome"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png"
        subtitle: "Network DNS & Ad-blocking"
        tag: "network"
        keywords: "dns adblock security"
        url: "https://adguard.example.com"
        target: "_blank"
        headers:
          Authorization: "Basic <sanitized_auth_header>"

      - name: "Portainer"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/portainer-pink.png"
        subtitle: "Docker Containers"
        url: "https://portainer.example.com"
        target: "_blank"
        type: "Portainer"
        endpoint: "https://portainer.example.com"
        apikey: "replace_me"
        # Click → goes to portainer.example.com
        # Stats → fetched from portainer.example.com API

      - name: "Homebridge"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homebridge.png"
        subtitle: "HomeKit Bridge"
        url: "https://hb.example.com"
        target: "_blank"
        type: "Ping"
      
      - name: "Home Assistant"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png"
        subtitle: "Smart home"
        url: "https://ha.example.com"
        target: "_blank"
        type: "HomeAssistant"
        apikey: "replace_me"
      
      - name: "Beszel"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/beszel.png"
        subtitle: "Performance dashboard"
        url: "https://perf.example.com"
        target: "_blank"
        type: "Ping"

  - name: "Media Server 🎬"
    icon: "fas fa-film"
    items:
      - name: "Tracearr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tracearr.png"
        subtitle: "Plex & Jellyfin Statistics"
        url: "https://tracearr.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"

      - name: "Plex"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png"
        url: "https://plex.example.com"
        target: "_blank"
        type: "Tautulli"
        endpoint: "https://tautulli.example.com"
        apikey: "replace_me"
        # Click → goes to plex.example.com
        # Stats → fetched from internal Tautulli IP

      # - name: "Tautulli"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tautulli.png"
      #   subtitle: "Plex Statistics"
      #   url: "https://tautulli.example.com"
      #   target: "_blank"
      #   type: "Ping"
      #   method: "GET"

      - name: "Jellyfin"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png"
        url: "https://jelly.example.com"
        target: "_blank"
        type: "Emby"
        endpoint: "https://jelly.example.com"
        apikey: "replace_me"
        libraryType: "series"
      
      - name: "Navidrome"
        subtitle: "Music Player"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/navidrome.png"
        url: "https://music.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"
      
      - name: "Audiobookshelf"
        subtitle: "Podcasts and Audiobooks"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/audiobookshelf.png"
        url: "https://podcasts.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"

  - name: "Downloads 📥"
    icon: "fas fa-download"
    items:
      - name: "Copyparty 🎉"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/copyparty.png"
        subtitle: "File Manager"
        url: "https://files.example.com"
        endpoint: "https://files.example.com/_homer/health"
        target: "_blank"
        type: "Ping"
        method: "GET"

      - name: "qBitTorrent"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png"
        subtitle: "Torrent Client (VPN)"
        url: "https://qbit.example.com"
        target: "_blank"
        type: "qBittorrent"
        rateInterval: 2000 # Interval for updating the download and upload rates.
        torrentInterval: 5000 # Interval for updating the torrent count.

      # - name: "Transmission"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/transmission.png"
      #   subtitle: "Torrent Client (VPN)"
      #   url: "https://trsm.example.com/transmission"
      #   target: "_blank"
      #   type: "Transmission"
      #   endpoint: "https://trsm.example.com/transmission/rpc"

      - name: "MeTube"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/metube.png"
        subtitle: "YouTube Downloader"
        url: "https://metube.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"
      
      - name: "Music Grabber"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/squeezebox-server.png"
        subtitle: "Music Downloader"
        url: "https://music-dl.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"

  - name: "Home 🏠"
    icon: "fas fa-house"
    items:
      - name: "Mealie"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mealie.png"
        subtitle: "Receipe Manager"
        url: "https://recipes.example.com"
        target: "_blank"
        type: "Mealie"
        apikey: "replace_me"

      - name: "Immich"
        type: "Immich"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png"
        url: "https://photos.example.com"
        apikey: "replace_me"

      - name: "Paperless"
        type: "PaperlessNG"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png"
        url: "https://pprless.example.com"
        apikey: "replace_me"

      # - name: "Actual"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/actual-budget.png"
      #   subtitle: "Budgeting"
      #   url: "https://budget.example.com"
      #   target: "_blank"
      #   type: "Ping"
      #   method: "GET"

  - name: "Productivity 📝"
    icon: "fas fa-tasks"
    items:
      # - name: "Habits"
      #   logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/habitsync.png"
      #   subtitle: "Habit Tracker"
      #   url: "https://habits.example.com"
      #   target: "_blank"
      #   type: "Ping"
      #   method: "GET"

      - name: "Kan"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/trello.png"
        subtitle: "Kanban Boards"
        url: "https://kanban.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"

      - name: "Karakeep"
        logo: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/karakeep.png"
        subtitle: "Bookmarks"
        url: "https://bookmarks.example.com/favicon.ico"
        target: "_blank"
        type: "Ping"

  - name: "Tools & Utilities 🛠️ "
    icon: "fas fa-toolbox"
    items:
      - name: "Apache Superset"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/apache-superset.png"
        subtitle: "Data visualization"
        url: "https://data-viz.example.com"
        target: "_blank"
        type: "Ping"

      - name: "Draw IO"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/draw-io.png"
        subtitle: "Architecture Diagrams"
        url: "https://diagram.example.com"
        target: "_blank"
        type: "Ping"
      
      - name: "Excalidraw"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/excalidraw.png"
        subtitle: "Whiteboarding"
        url: "https://draw.example.com"
        target: "_blank"
        type: "Ping"
      
      - name: "Open WebUI"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/open-webui.png"
        subtitle: "AI Chat UI"
        url: "https://chat.example.com"
        target: "_blank"
        type: "Ping"

      - name: "n8n"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/n8n.png"
        subtitle: "Automation & AI"
        url: "https://n8n.example.com"
        target: "_blank"
        type: "Ping"

      - name: "Bento PDF Tools"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bentopdf.png"
        subtitle: "PDF Utilities"
        url: "https://pdftools.example.com/index.html#tools-header"
        target: "_blank"
        type: "Ping"

      - name: "IT Tools"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/it-tools.png"
        subtitle: "Developer Utilities"
        url: "https://ittools.example.com"
        target: "_blank"
        type: "Ping"

      - name: "Network Tools"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/guacamole.png"
        subtitle: "Network Utilities"
        url: "https://nettools.example.com"
        target: "_blank"
        type: "Ping"

  - name: "Arr 🏴☠️"
    icon: "fas fa-sailboat"
    items:
      - name: "Prowlarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png"
        subtitle: "Indexer Manager (VPN)"
        url: "https://prowlarr.example.com"
        target: "_blank"
        type: "Prowlarr"
        endpoint: "https://prowlarr.example.com"
        apikey: "replace_me"
        # Click → goes to prowlarr.example.com
        # Stats → fetched from internal IP

      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png"
        subtitle: "Movie management"
        url: "https://radarr.example.com"
        target: "_blank"
        type: "Radarr"
        endpoint: "https://radarr.example.com"
        apikey: "replace_me"

      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png"
        subtitle: "Series management"
        url: "https://sonarr.example.com"
        target: "_blank"
        type: "Sonarr"
        endpoint: "https://sonarr.example.com"
        apikey: "replace_me"

      - name: "Lidarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/lidarr.png"
        subtitle: "Music management"
        url: "https://lidarr.example.com"
        target: "_blank"
        type: "Lidarr"
        endpoint: "https://lidarr.example.com"
        apikey: "replace_me"

      - name: "Bazarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bazarr.png"
        subtitle: "Subtitle management"
        url: "https://bazarr.example.com"
        target: "_blank"
        type: "Ping"
        method: "GET"
        endpoint: "https://bazarr.example.com"

      - name: "Seerr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyseerr.png"
        subtitle: "Media request manager"
        url: "https://seerr.example.com"
        target: "_blank"
        type: "Ping"

      # - name: "Profilarr"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/profilarr.png"
      #   subtitle: "Quality profile manager"
      #   url: "https://profilarr.example.com"
      #   target: "_blank"
      #   type: "Ping"
